server:
  port: 9090
  
acceptableErrorStatus: OK

application:
  oauth:
    configuration:
      client-secret: clientSecret 
      client-id: carServiceClient

resource-server:
  url: http://localhost:9092
          